insert into departments (name)
values  ('Business Development'),
        ('Customer Support'),
        ('Engineering'),
        ('Finance'),
        ('Human Resources'),
        ('IT Support'),
        ('Legal'),
        ('Marketing'),
        ('Operations'),
        ('Procurement'),
        ('Product Management'),
        ('Quality Assurance'),
        ('Research and Development'),
        ('Sales'),
        ('Service');

insert into roles (title, salary, department_id)
values  ('Sale Lead', 100000, 4),
        ('Salesperson', 80000, 4),
        ('Lead Engineer', 150000, 1),
        ('Software Engineer', 120000, 1),
        ('Account Manager', 160000, 2),
        ('Accountant', 125000, 2),
        ('Legal Team Lead', 250000, 3),
        ('Lawyer', 190000, 3),
        ('Customer Service', 100000, 10),
        ('Service Agent', 80000, 10),
        ('HR Manager', 90000, 5),
        ('HR Specialist', 60000, 5),
        ('Marketing Manager', 110000, 7),
        ('Marketing Specialist', 70000, 7),
        ('IT Support Specialist', 70000, 6),
        ('IT Support Manager', 110000, 6),
        ('Research Scientist', 120000, 13),
        ('Product Manager', 130000, 11),
        ('Customer Support Lead', 90000, 2),
        ('Quality Assurance Engineer', 90000, 12),
        ('Business Development Manager', 140000, 1),
        ('Operations Manager', 130000, 8),
        ('Procurement Specialist', 80000, 9);

insert into employees(first_name, last_name, role_id, manager_id)
values  ('John', 'Doe', 1, null),
        ('Mike', 'Chan', 2, 1),
        ('Ashley', 'Rodriguez', 3, null),
        ('Kevin', 'Tupik', 4, 3),
        ('Kunal', 'Singh', 5, null),
        ('Malia', 'Brown', 6, 5),
        ('Sarah', 'Johnson', 7, null),
        ('David', 'Smith', 8, 7),
        ('Emma', 'Wilson', 9, null),
        ('Liam', 'Taylor', 10, 9),
        ('Olivia', 'Anderson', 11, null),
        ('Noah', 'Thomas', 12, 11),
        ('Ava', 'Moore', 13, null),
        ('Sophia', 'Martin', 14, 13),
        ('Isabella', 'Clark', 15, null),
        ('Mason', 'Lee', 16, 15),
        ('Mia', 'Walker', 17, null),
        ('Lucas', 'Hall', 18, 17),
        ('Ethan', 'Harris', 19, null),
        ('Harper', 'Young', 20, 19),
        ('Ella', 'King', 21, null),
        ('James', 'Wright', 22, 21);     