insert into departments (name)
values  ('Business Development'),
        ('Customer Support'),
        ('Engineering'),
        ('Finance'),
        ('Human Resources'),
        ('IT Support'),
        ('Legal'),
        ('Marketing'),
        ('Operations'),
        ('Procurement'),
        ('Product Management'),
        ('Quality Assurance'),
        ('Research and Development'),
        ('Sales'),
        ('Service');

insert into roles (title, salary, department_id)
values  ('Business Development Manager', 140000, 1),
        ('Business Analyst', 100000, 1),
        ('Customer Support Manager', 90000, 2),
        ('Customer Support Specialist', 70000, 2),
        ('Chief Engineer', 180000, 3),
        ('Mechanical Engineer', 110000, 3),
        ('Finance Director', 160000, 4),
        ('Financial Analyst', 85000, 4),
        ('HR Director', 150000, 5),
        ('HR Coordinator', 65000, 5),
        ('IT Support Specialist', 70000, 6),
        ('IT Support Manager', 110000, 6),
        ('Chief Legal Officer', 200000, 7),
        ('Paralegal', 60000, 7),
        ('Marketing Director', 140000, 8),
        ('Marketing Coordinator', 60000, 8),
        ('Operations Manager', 130000, 9),
        ('Operations Specialist', 75000, 9),
        ('Procurement Manager', 120000, 10),
        ('Procurement Specialist', 70000, 10);

insert into employees(first_name, last_name, role_id, manager_id)
values  ('Alice', 'Johnson', 1, null),
        ('Bob', 'Smith', 2, 1),       
        ('Carol', 'Davis', 3, null),
        ('David', 'Martinez', 4, 3),
        ('Eve', 'Brown', 5, null),
        ('Frank', 'Wilson', 6, 5),
        ('Grace', 'Moore', 7, null),
        ('Hank', 'Taylor', 8, 7),
        ('Ivy', 'Anderson', 9, null),
        ('Jack', 'Thomas', 10, 9),
        ('Kate', 'Jackson', 11, null),
        ('Liam', 'White', 12, 11),
        ('Mia', 'Harris', 13, null),
        ('Nate', 'Martin', 14, 13),
        ('Olivia', 'Thompson', 15, null),
        ('Paul', 'Garcia', 16, 15),
        ('Quinn', 'Martinez', 17, null),
        ('Rachel', 'Clark', 18, 17),
        ('Steve', 'Rodriguez', 19, null),
        ('Tina', 'Lewis', 20, 19);